version: '3'
services:
  redis:
    image: "redis:alpine"
    networks:
      - webnet
  mathbook:
    build:
      context: .
    depends_on:
      - redis
    environment:
      PROTOCOL: http
      HOST: 0.0.0.0
      PORT: 4000
      REDIS_HOST: redis
    ports:
      - "4000:4000"
    networks:
      - webnet
networks: 
  webnet: